import styles from "@/app/[locale]/layout.module.css";
import LanguagePicker from "@/components/LanguagePicker";
import MainNavigation from "@/components/MainNavigation";
import { images } from "@/constants/";
import { NextIntlClientProvider } from "next-intl";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ReactNode } from "react";
import "./globals.css";

export const metadata = {
  title: "Oishii",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "nl" }];
}

type RootLayoutPropType = {
  children: ReactNode;
  params: {
    locale: string;
  };
};

const RootLayout = async ({
  children,
  params: { locale },
}: RootLayoutPropType) => {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <header className={styles.header}>
            <div className={styles.container}>
              <Image
                src={images.OISHII_LOGO.src}
                className={styles.logo}
                alt="Oishii logo"
                width={80}
                height={50}
              />
              <MainNavigation />
              <LanguagePicker />
            </div>
          </header>
          <main>{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
